# Site settings
title: Trading Post Market
description: A cozy winter farmers' market in Green Bay, WI. Experience and support local food culture, education, and creativity.

# Build settings
markdown: kramdown
permalink: pretty
